# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            '125th Anniversary'
description:      'Celebrating 125 Years of the Library Building'
url:              'https://minicomp.github.io'
baseurl:          '/125-anniversary'
copyright:        'Pratt Institute Libraries, 2022'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
incremental: true
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  125Exhibit: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'anniversary_item' # the layout for the pages to use
    metadata:
      source: '125Exhibit.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/125LibraryBuilding' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      125Exhibit:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - work_creator
          - label
          - caption
          - type
          - location
          - _date
          - style
          - description
          - image_creator
          - image_date
          - image_type
          - image_description
          - collection

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Explore'
    sub:
      - label: 'Pratt Institute Free Library'
        link: '/explore/pratt-institute-free-library/'
      - label: 'A New Home for the Library'
        link: '/explore/a-new-home-for-the-library/'
      - label: 'The Library School'
        link: '/explore/the-library-school/'
      - label: 'The Library Museum'
        link: '/explore/the-library-museum/'
      - label: "The Children's Reading Room and Library Park"
        link: '/explore/the-childrens-reading-room-and-library-park/'
      - label: 'A New Era For the Library'
        link: '/explore/a-new-era-for-the-library/'
      - label: 'Renovations to the Library Building'
        link: '/explore/renovations-to-the-library-building/'
      - label: 'The Centennial'
        link: '/explore/the-centennial/'
      - label: 'The Libraries Today'
        link: '/explore/the-libraries-today/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'Digital Exhibits'
      link: 'https://specialcollections.pratt.edu'
    - label: 'Institute Libraries'
      link: 'https://library.pratt.edu'
    - label: 'Contact'
      link: 'https://gitter.im/minicomp/wax/'
  logos:
    - img: '/img/logo.png'

# FIN
